// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-GchO9l9vCzxo_phkV0BKwZiEVRkXjGk',
    appId: '1:403753103671:web:12b043c856eafbbae32ab2',
    messagingSenderId: '403753103671',
    projectId: 'glowguard-160b8',
    authDomain: 'glowguard-160b8.firebaseapp.com',
    storageBucket: 'glowguard-160b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApo3Q_YqNn21qQxQ90oLTa0ONL3LDewFI',
    appId: '1:403753103671:android:effd069eddefc98be32ab2',
    messagingSenderId: '403753103671',
    projectId: 'glowguard-160b8',
    storageBucket: 'glowguard-160b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmJA0cfVTjYD7g9cLML0hU-ahcgyNzJCg',
    appId: '1:403753103671:ios:7d5a6b8e03e5e4a9e32ab2',
    messagingSenderId: '403753103671',
    projectId: 'glowguard-160b8',
    storageBucket: 'glowguard-160b8.firebasestorage.app',
    iosBundleId: 'com.example.glowguardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmJA0cfVTjYD7g9cLML0hU-ahcgyNzJCg',
    appId: '1:403753103671:ios:7d5a6b8e03e5e4a9e32ab2',
    messagingSenderId: '403753103671',
    projectId: 'glowguard-160b8',
    storageBucket: 'glowguard-160b8.firebasestorage.app',
    iosBundleId: 'com.example.glowguardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-GchO9l9vCzxo_phkV0BKwZiEVRkXjGk',
    appId: '1:403753103671:web:2a2a629e887d9d54e32ab2',
    messagingSenderId: '403753103671',
    projectId: 'glowguard-160b8',
    authDomain: 'glowguard-160b8.firebaseapp.com',
    storageBucket: 'glowguard-160b8.firebasestorage.app',
  );
}
